function [Xs] = GlobalImprovement(MFEA, Config)

    % Space Filling Population
    Xs = [];

    for j=1:Config.SpaceFilling.Loop

        % Select Filling Strategy
        switch Config.SpaceFilling.Strategy

            case 1
                [Xs_fill, ~, ~, ~] = fill_avg([MFEA.Xs; Xs], Config.SpaceFilling.Nadd, ...
                                                       Config.Domain.Precision, ... 
                                                       Config.Domain.Initial, ... 
                                                       Config.Domain.Final, ...
                                                       Config.SpaceFilling.lower_bound, ...
                                                       Config.SpaceFilling.upper_bound, ...
                                                       Config.SpaceFilling.deep_level, ...
                                                       Config.SpaceFilling.behavior, ...
                                                       Config.SpaceFilling.grid, ...
                                                       Config.SpaceFilling.D_factor, ...
                                                       Config.SpaceFilling.R_factor);

            case 2
                [Xs_fill, ~, ~, ~] = fill_Nsphere([MFEA.Xs; Xs], Config.SpaceFilling.Nadd, ...
                                                       Config.Domain.Precision, ... 
                                                       Config.Domain.Initial, ... 
                                                       Config.Domain.Final, ...
                                                       Config.SpaceFilling.lower_bound, ...
                                                       Config.SpaceFilling.upper_bound, ...
                                                       Config.SpaceFilling.deep_level, ...
                                                       Config.SpaceFilling.behavior, ...
                                                       Config.SpaceFilling.grid, ...
                                                       Config.SpaceFilling.D_factor, ...
                                                       Config.SpaceFilling.R_factor);

            case 3
                [Xs_fill, ~, ~, ~] = fill_tri([MFEA.Xs; Xs], Config.SpaceFilling.Nadd, ...
                                                       Config.Domain.Precision, ... 
                                                       Config.Domain.Initial, ... 
                                                       Config.Domain.Final, ...
                                                       Config.SpaceFilling.lower_bound, ...
                                                       Config.SpaceFilling.upper_bound, ...
                                                       Config.SpaceFilling.deep_level, ...
                                                       Config.SpaceFilling.behavior, ...
                                                       Config.SpaceFilling.grid, ...
                                                       Config.SpaceFilling.D_factor, ...
                                                       Config.SpaceFilling.R_factor);

        end

        % Merge Populations
        Xs = [Xs; Xs_fill];

    end
                
end