function [Xs] = LocalImprovement(Parent, MFEA, Config)

    % Current Population Selection
    dTrust     = 5;
    dReclusion = 5;

    ParentRM = RoundM(Parent, Config.Domain.Precision);

    [unreliable, recluse, popular, riser, ~] = SurrogateMetric(ParentRM, MFEA.Xs, dTrust, dReclusion);

    Xl = [unreliable; recluse; popular; riser];

    % Identify Region
    [Xs_min, Xs_max] = IdentifyRegion(Xl, Config.Domain.Initial, ...
                                      Config.Domain.Final, ...
                                      Config.Dimension.Number, ...
                                      Config.Domain.Precision, ...
                                      Config.Surrogates.Padding);                

    % Space Filling Population         
    Xs = [];

    for j=1:Config.SpaceFilling.Loop

        % Select Filling Strategy
        switch Config.SpaceFilling.Strategy

            case 1
                [Xs_fill, ~, metric_SF_n, ~] = fill_avg([MFEA.Xs; Xs], Config.SpaceFilling.Nadd, ...
                                                       Config.Domain.Precision, Xs_min, Xs_max, ...
                                                       Config.SpaceFilling.lower_bound, ...
                                                       Config.SpaceFilling.upper_bound, ...
                                                       Config.SpaceFilling.deep_level, ...
                                                       Config.SpaceFilling.behavior, ...
                                                       Config.SpaceFilling.grid, ...
                                                       Config.SpaceFilling.D_factor, ...
                                                       Config.SpaceFilling.R_factor);

            case 2
                [Xs_fill, ~, metric_SF_n, ~] = fill_Nsphere([MFEA.Xs; Xs], Config.SpaceFilling.Nadd, ...
                                                       Config.Domain.Precision, Xs_min, Xs_max, ...
                                                       Config.SpaceFilling.lower_bound, ...
                                                       Config.SpaceFilling.upper_bound, ...
                                                       Config.SpaceFilling.deep_level, ...
                                                       Config.SpaceFilling.behavior, ...
                                                       Config.SpaceFilling.grid, ...
                                                       Config.SpaceFilling.D_factor, ...
                                                       Config.SpaceFilling.R_factor);

            case 3
                [Xs_fill, ~, metric_SF_n, ~] = fill_tri([MFEA.Xs; Xs], Config.SpaceFilling.Nadd, ...
                                                       Config.Domain.Precision, Xs_min, Xs_max, ...
                                                       Config.SpaceFilling.lower_bound, ...
                                                       Config.SpaceFilling.upper_bound, ...
                                                       Config.SpaceFilling.deep_level, ...
                                                       Config.SpaceFilling.behavior, ...
                                                       Config.SpaceFilling.grid, ...
                                                       Config.SpaceFilling.D_factor, ...
                                                       Config.SpaceFilling.R_factor);

        end

        % Warning: Could not find any new points in the desired region.
        if (metric_SF_n == 0)

            % Increase Padding
            Config.Surrogates.Padding = Config.Surrogates.Padding * 1.05;

            % Update Region
            [Xs_min, Xs_max] = IdentifyRegion(Xl, Config.Domain.Initial, Config.Domain.Final, ...
                                              Config.Domain.Precision, Config.Surrogates.Padding); 

        else

            % Merge Populations
            Xs = [Xs; Xs_fill];

        end

    end

end